window.CLOTHES_CONFIG = {
  "categories": [
    { "id": "skin",  "label": "Skin",  "multi": false },
    { "id": "face",  "label": "Face",  "multi": false },
    { "id": "hair",  "label": "Hair",  "multi": false },
    { "id": "dress", "label": "Dress", "multi": false },
    { "id": "top",   "label": "Top",   "multi": false },
    { "id": "pants", "label": "Pants", "multi": false },
    { "id": "coat",  "label": "Coat",  "multi": false },
    { "id": "shoes", "label": "Shoes", "multi": false },
    { "id": "acc",   "label": "Acc",   "multi": true  }
  ],
  "items": [
    { "id": "Skin1",          "cat": "skin",  "outfit": "Skin 1",   "z": 1,  "price": { "q": 0  } },
    { "id": "Skin2",          "cat": "skin",  "outfit": "Skin 2",   "z": 1,  "price": { "q": 0  } },
    { "id": "Skin3",          "cat": "skin",  "outfit": "Skin 3",   "z": 1,  "price": { "q": 0  } },
    { "id": "Skin4",          "cat": "skin",  "outfit": "Skin 4",   "z": 1,  "price": { "q": 0  } },
    { "id": "Skin5",          "cat": "skin",  "outfit": "Skin 5",   "z": 1,  "price": { "q": 0  } },
    { "id": "Face_Bertha",    "cat": "face",  "outfit": "Bertha",   "z": 7,  "price": { "a": 3  } },
    { "id": "Face_Courtney",  "cat": "face",  "outfit": "Courtney", "z": 7,  "price": { "a": 5  } },
    { "id": "Face_Lalicka",   "cat": "face",  "outfit": "Lalicka",  "z": 7,  "price": { "a": 3  } },
    { "id": "Face_Laura",     "cat": "face",  "outfit": "Laura",    "z": 7,  "price": { "q": 35 } },
    { "id": "Face_Pajama",    "cat": "face",  "outfit": "Pajama",   "z": 7,  "price": { "q": 0  } },
    { "id": "Hair_Bertha",    "cat": "hair",  "outfit": "Bertha",   "z": 8,  "price": { "q": 20 } },
    { "id": "Hair_Courtney",  "cat": "hair",  "outfit": "Courtney", "z": 8,  "price": { "a": 5  } },
    { "id": "Hair_Lalicka",   "cat": "hair",  "outfit": "Lalicka",  "z": 8,  "price": { "q": 30 } },
    { "id": "Hair_Amy",       "cat": "hair",  "outfit": "Amy",      "z": 8,  "price": { "q": 30 } },
    { "id": "Hair_Laura",     "cat": "hair",  "outfit": "Laura",    "z": 8,  "price": { "q": 25 } },
    { "id": "Hair_Pajama",    "cat": "hair",  "outfit": "Pajama",   "z": 8,  "price": { "q": 0  } },
    { "id": "Hair_Dafna",     "cat": "hair",  "outfit": "Dafna",    "z": 8,  "price": { "q": 20 } },
    { "id": "Dress_Bertha",   "cat": "dress", "outfit": "Bertha",   "z": 4,  "price": { "q": 20 } },
    { "id": "Dress_Courtney", "cat": "dress", "outfit": "Courtney", "z": 4,  "price": { "a": 4  } },
    { "id": "Dress_Lalicka",  "cat": "dress", "outfit": "Lalicka",  "z": 4,  "price": { "q": 25 } },
    { "id": "Dress_Amy",      "cat": "dress", "outfit": "Amy",      "z": 4,  "price": { "q": 25 } },
    { "id": "Top_Laura",      "cat": "top",   "outfit": "Laura",    "z": 5,  "price": { "q": 15 } },
    { "id": "Top_Pajama",     "cat": "top",   "outfit": "Pajama",   "z": 5,  "price": { "q": 0  } },
    { "id": "Top_Dafna",      "cat": "top",   "outfit": "Dafna",    "z": 5,  "price": { "q": 15 } },
    { "id": "Pants_Courtney", "cat": "pants", "outfit": "Courtney", "z": 4,  "price": { "q": 25 } },
    { "id": "Pants_Laura",    "cat": "pants", "outfit": "Laura",    "z": 4,  "price": { "q": 15 } },
    { "id": "Pants_Pajama",   "cat": "pants", "outfit": "Pajama",   "z": 4,  "price": { "q": 0  } },
    { "id": "Pants_Dafna",    "cat": "pants", "outfit": "Dafna",    "z": 4,  "price": { "q": 15 } },
    { "id": "Coat_Bertha",    "cat": "coat",  "outfit": "Bertha",   "z": 6,  "price": { "q": 20 } },
    { "id": "Coat_Courtney",  "cat": "coat",  "outfit": "Courtney", "z": 6,  "price": { "q": 30 } },
    { "id": "Shoes_Bertha",   "cat": "shoes", "outfit": "Bertha",   "z": 3,  "price": { "q": 20 } },
    { "id": "Shoes_Courtney", "cat": "shoes", "outfit": "Courtney", "z": 3,  "price": { "a": 5  } },
    { "id": "Shoes_Lalicka",  "cat": "shoes", "outfit": "Lalicka",  "z": 3,  "price": { "q": 15 } },
    { "id": "Shoes_Amy",      "cat": "shoes", "outfit": "Amy",      "z": 3,  "price": { "q": 20 } },
    { "id": "Shoes_Laura",    "cat": "shoes", "outfit": "Laura",    "z": 3,  "price": { "q": 10 } },
    { "id": "Shoes_Dafna",    "cat": "shoes", "outfit": "Dafna",    "z": 3,  "price": { "q": 15 } },
    { "id": "Acc_1_Bertha",   "cat": "acc",   "outfit": "Bertha",   "z": 2,  "price": { "q": 5  } },
    { "id": "Acc_1_Dafna",    "cat": "acc",   "outfit": "Dafna",    "z": 9,  "price": { "q": 10 } },
    { "id": "Acc_2_Dafna",    "cat": "acc",   "outfit": "Dafna",    "z": 2,  "price": { "q": 5  } },
    { "id": "Acc_1_Courtney", "cat": "acc",   "outfit": "Courtney", "z": 2,  "price": { "a": 2  } },
    { "id": "Acc_2_Courtney", "cat": "acc",   "outfit": "Courtney", "z": 10, "price": { "a": 2  } },
    { "id": "Acc_3_Courtney", "cat": "acc",   "outfit": "Courtney", "z": 2,  "price": { "a": 5  } },
    { "id": "Acc_4_Courtney", "cat": "acc",   "outfit": "Courtney", "z": 2,  "price": { "a": 3  } },
    { "id": "Acc_1_Lalicka",  "cat": "acc",   "outfit": "Lalicka",  "z": 2,  "price": { "q": 5  } },
    { "id": "Acc_2_Lalicka",  "cat": "acc",   "outfit": "Lalicka",  "z": 2,  "price": { "q": 10 } },
    { "id": "Acc_1_Laura",    "cat": "acc",   "outfit": "Laura",    "z": 9,  "price": { "a": 3  } }
  ],
  "outfits": {
    "Bertha":   ["Face_Bertha","Hair_Bertha","Dress_Bertha","Coat_Bertha","Shoes_Bertha","Acc_1_Bertha"],
    "Courtney": ["Face_Courtney","Hair_Courtney","Dress_Courtney","Coat_Courtney","Pants_Courtney","Shoes_Courtney","Acc_1_Courtney","Acc_2_Courtney","Acc_3_Courtney","Acc_4_Courtney"],
    "Lalicka":  ["Face_Lalicka","Hair_Lalicka","Dress_Lalicka","Shoes_Lalicka","Acc_1_Lalicka","Acc_2_Lalicka"],
    "Laura":    ["Face_Laura","Hair_Laura","Pants_Laura","Top_Laura","Shoes_Laura","Acc_1_Laura"],
    "Pajama":   ["Face_Pajama","Hair_Pajama","Top_Pajama","Pants_Pajama"],
    "Dafna":    ["Hair_Dafna","Top_Dafna","Pants_Dafna","Shoes_Dafna","Acc_1_Dafna","Acc_2_Dafna"],
    "Amy":      ["Hair_Amy","Dress_Amy","Shoes_Amy"]
  },
  "starters": ["Skin1","Skin2","Skin3","Skin4","Skin5","Face_Pajama","Hair_Pajama","Top_Pajama","Pants_Pajama"]
};
